apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k3s-pool
  namespace: demo
spec:
  addresses:
    - <YOUR_IP_RANGE>
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k3s-adv
  namespace: demo
